# ~/.config/starship.toml

# Inserts a blank line between shell prompts

add_newline = true

# Command Time out

scan_timeout = 10000
command_timeout = 10000

# Change the default prompt format

format = """
[â•­â•´](bold purple)$os\
| $username\
$directory $fill $shellî‚³ \
$git_branch\
$git_status\
$lua\
$terraform\
$vagrant\
$docker_context\
$helm\
$python\
$nodejs\
$ruby\
$kubernetes\
$kubernetes
[â•°â”€](bold red)$character\
"""
# Right_format

# right_format = """ -- re-enabe for time and battery percentage
# $time\
# $cmd_duration
# $battery\
# """

# A continuation prompt that displays two filled in arrows

continuation_prompt = 'â–¶â–¶ '

# Change the default prompt characters

[character]
success_symbol = "[î˜‚](238)"
error_symbol = "[î¯ ](fg:9)"
# error_symbol = "[ï‘ï”¯](red)"


[profiles]
short = """
ï““ $directory $fill \
 $time \
\n ó°¤¹ î˜¡î‚°î‚± \
"""

# Change default Fill style
[fill]
# symbol = '=-='
symbol = ' '

# No need for env variables as starship provides a way to show your current distro

[os]
disabled = false
style = "fg:255"
format = "[$symbol]($style)"

[os.symbols]
Windows = "î˜ª "
Linux = ""
Arch = "ó°£‡ "
Debian ="î½ "
Fedora ="ïŒŠ "
Ubuntu = "ïŒ› "
EndeavourOS = "ïŒ¢ "

#Directory settings

[directory]
truncation_length = 5
truncation_symbol = "â€¦/"
home_symbol = "| ï€• ~"
read_only_style = "197"
read_only = " ï€£ "
format = " at [$path]($style)[$read_only]($read_only_style)"

# Shows the username

[username]
style_user = "bold blue"
style_root = "bold purple"
format = "ğŸ’œ [$user]($style)"
disabled = false  # disable in powershell
show_always = true

# Shows the prompt for the root user
#[root]
#format = "[$user]($style) "
#disabled = false
#show_always = true

# Shows the shell

[shell]
bash_indicator = "bash î¯Š _"
fish_indicator = "ó°ˆº ó±¢º "
# zsh_indicator = "ïŠ• _"
zsh_indicator = "zsh ïŠ• _"
powershell_indicator = "ó°¨Š "
ion_indicator ="î™« "
elvish_indicator = "î˜¬ "
tcsh_indicator = "ó°“¸ "
xonsh_indicator = "ï…© "
cmd_indicator = "î¯„ "
nu_indicator = "ó±„† "
unknown_indicator = "î¯ƒ "
style = "cyan bold"
# format = "îš‘ó°«µó°«²ó±¦ó±¦â€¢ [$indicator]($style) "
format = "[$indicator]($style) "
disabled = false

# Shows the battery

[battery]
full_symbol = "â€¢"
charging_symbol = "â‡¡"
discharging_symbol = "â‡£"
format = " [$symbol $percentage ]($style) "
disabled = false
#show_always = true

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

[[battery.display]] # 'red' style and discharging_symbol when capacity is between 20% and 30%
threshold = 20
style = 'red'

[[battery.display]] # 'light red' style and discharging_symbol when capacity is between 20% and 30%
threshold = 30
style = 'light red'

[[battery.display]] # 'light yellow' style and discharging_symbol when  capacity is between 30% and 40%
threshold = 40
style = 'light yellow'

[[battery.display]] # 'yellow' style and discharging_symbol when  capacity is between 40% and 50%
threshold = 50
style = 'yellow'

[[battery.display]] # 'bold yellow' style and discharging_symbol when  capacity is between 50% and 60%
threshold = 60
style = 'bold yellow'

[[battery.display]] # 'light green' style and discharging_symbol when  capacity is between 60% and 70%
threshold = 60
style = "70"

[[battery.display]] # 'green' style and discharging_symbol when  capacity is between 70% and %80
threshold = 70
style = "green"

[[battery.display]] # 'bold green' style and discharging_symbol when  capacity is between 80% and 90%
threshold = 80
style = "bold green"

[[battery.display]] # 'cyan' style and discharging_symbol when  capacity is between 90% and 100%
threshold = 90
style = "cyan"

[[battery.display]] # 'bold cyan' style and discharging_symbol when  capacity is between 100% and 110%
threshold = 100
style = "bold cyan"

# Shows the time

[time]
disabled = false
style = "253"
format = "ó±‘‚(255) [$time]($style) "

# Shows the CMD duration

[cmd_duration]
min_time = 10
format = "| ó°”š [$duration]($style) "
style = "yellow"

# Shows the app directory/contents

[git_branch]
symbol = "ó°Š¢ ï‡“ (yellow)"
format = "on [$symbol î‚  $branch]($style) "
truncation_length = 7
truncation_symbol = "â€¦/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = " ï† "
untracked = " ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = " ó°— "
modified = " ï„ "
staged = '[++\($count\)](green)'
renamed = " ó°–· "
deleted = " ï€” "

[lua]
format = "via [ó°¢± ó°† lua $version]($style)"

[terraform]
format = "via [ó±¢ ï”… terraform $version]($style) ï¥‚ [$workspace]($style)"

[vagrant]
format = "via [îš¬ ï„µ vagrant $version]($style)"

[docker_context]
format = "via [ó°¡¨ ïŒˆ $context](bold blue)"
 
[helm]
format = "via [ó°·€ ïˆš $version](bold purple)"

[python]
symbol = "[ó°Œ  ó±” ](blue)"
python_binary = "python3"

[nodejs]
format = "via [îœ™ ó°™ $version](bold green)"
disabled = true

[ruby]
format = "via [ó°« îˆ¾ $version]($style)"

[kubernetes]
format = 'on [ó° ³ ïˆš $context\($namespace\)](bold purple)'
disabled = false

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

